// This file is created by egg-ts-helper@1.25.7
// Do not modify this file!!!!!!!!!

import 'egg';
type AnyClass = new (...args: any[]) => any;
type AnyFunc<T = any> = (...args: any[]) => T;
type CanExportFunc = AnyFunc<Promise<any>> | AnyFunc<IterableIterator<any>>;
type AutoInstanceType<T, U = T extends CanExportFunc ? T : T extends AnyFunc ? ReturnType<T> : T> = U extends AnyClass ? InstanceType<U> : U;
import ExportActivity = require('../../../app/service/activity');
import ExportActivityExpand = require('../../../app/service/activityExpand');
import ExportAlicloudsms = require('../../../app/service/alicloudsms');
import ExportCard = require('../../../app/service/card');
import ExportCardEntity = require('../../../app/service/card_entity');
import ExportCardHistory = require('../../../app/service/card_history');
import ExportCardLevel = require('../../../app/service/card_level');
import ExportChina = require('../../../app/service/china');
import ExportCoach = require('../../../app/service/coach');
import ExportCompany = require('../../../app/service/company');
import ExportCompanyPackage = require('../../../app/service/company_package');
import ExportContractTemplete = require('../../../app/service/contract_templete');
import ExportCoupon = require('../../../app/service/coupon');
import ExportCourse = require('../../../app/service/course');
import ExportCourseExpand = require('../../../app/service/courseExpand');
import ExportCourseCoach = require('../../../app/service/course_coach');
import ExportCourseLabel = require('../../../app/service/course_label');
import ExportCoursePackageRelate = require('../../../app/service/course_package_relate');
import ExportCourseSchedule = require('../../../app/service/course_schedule');
import ExportCourseType = require('../../../app/service/course_type');
import ExportEmail163 = require('../../../app/service/email163');
import ExportFaceDevice = require('../../../app/service/face_device');
import ExportFaceDeviceExtend = require('../../../app/service/face_deviceExtend');
import ExportGeographic = require('../../../app/service/geographic');
import ExportHome = require('../../../app/service/home');
import ExportIcons = require('../../../app/service/icons');
import ExportLabel = require('../../../app/service/label');
import ExportMember = require('../../../app/service/member');
import ExportMemberExpand = require('../../../app/service/memberExpand');
import ExportMemberBody = require('../../../app/service/member_body');
import ExportMemberCoachInvite = require('../../../app/service/member_coach_invite');
import ExportMemberCoupon = require('../../../app/service/member_coupon');
import ExportMemberMessage = require('../../../app/service/member_message');
import ExportMemberReservation = require('../../../app/service/member_reservation');
import ExportMemberReservationExpand = require('../../../app/service/member_reservation_expand');
import ExportMemberTracking = require('../../../app/service/member_tracking');
import ExportMigrate = require('../../../app/service/migrate');
import ExportOrder = require('../../../app/service/order');
import ExportOrderExpand = require('../../../app/service/orderExpand');
import ExportOrderContract = require('../../../app/service/order_contract');
import ExportOrderMain = require('../../../app/service/order_main');
import ExportOrderPayment = require('../../../app/service/order_payment');
import ExportOrderPaymentExpand = require('../../../app/service/order_payment_expand');
import ExportOrderRefund = require('../../../app/service/order_refund');
import ExportOrderSub = require('../../../app/service/order_sub');
import ExportPackageStore = require('../../../app/service/package_store');
import ExportPackages = require('../../../app/service/packages');
import ExportPackagesType = require('../../../app/service/packages_type');
import ExportPlaceOrder = require('../../../app/service/place_order');
import ExportStore = require('../../../app/service/store');
import ExportStoreRoom = require('../../../app/service/store_room');
import ExportStoreTask = require('../../../app/service/store_task');
import ExportSysCache = require('../../../app/service/sys_cache');
import ExportSysCacheExpand = require('../../../app/service/sys_cache_expand');
import ExportSysDepartment = require('../../../app/service/sys_department');
import ExportSysDictionary = require('../../../app/service/sys_dictionary');
import ExportSysLog = require('../../../app/service/sys_log');
import ExportSysMenu = require('../../../app/service/sys_menu');
import ExportSysMenuSysOperation = require('../../../app/service/sys_menu_sys_operation');
import ExportSysMenuSysRoleSysOperation = require('../../../app/service/sys_menu_sys_role_sys_operation');
import ExportSysMessage = require('../../../app/service/sys_message');
import ExportSysNavigation = require('../../../app/service/sys_navigation');
import ExportSysOperation = require('../../../app/service/sys_operation');
import ExportSysRole = require('../../../app/service/sys_role');
import ExportSysRoleSysUser = require('../../../app/service/sys_role_sys_user');
import ExportSysUser = require('../../../app/service/sys_user');
import ExportSysUserDutyRoster = require('../../../app/service/sys_user_duty_roster');
import ExportSysUserLabel = require('../../../app/service/sys_user_label');
import ExportSystem = require('../../../app/service/system');
import ExportTask = require('../../../app/service/task');
import ExportTaskRecord = require('../../../app/service/task_record');
import ExportTaskType = require('../../../app/service/task_type');
import ExportTest = require('../../../app/service/test');
import ExportTrainAction = require('../../../app/service/train_action');
import ExportTrainSchedulePhase = require('../../../app/service/train_schedule_phase');
import ExportTrainSchedulePhaseAction = require('../../../app/service/train_schedule_phase_action');
import ExportTrainScheduleUser = require('../../../app/service/train_schedule_user');
import ExportTrainTplPhase = require('../../../app/service/train_tpl_phase');
import ExportTrainTplPhaseAction = require('../../../app/service/train_tpl_phase_action');
import ExportTrainTplSchedule = require('../../../app/service/train_tpl_schedule');
import ExportUserRight = require('../../../app/service/user_right');
import ExportVerification = require('../../../app/service/verification');
import ExportWechatFormId = require('../../../app/service/wechat_form_id');
import ExportWxpayRecord = require('../../../app/service/wxpay_record');
import ExportCodeIndex = require('../../../app/service/code/index');
import ExportMessageOrderSuccess = require('../../../app/service/message/order_success');
import ExportPaymentWxpay = require('../../../app/service/payment/wxpay');
import ExportShellCart = require('../../../app/service/shell/cart');
import ExportShellMember = require('../../../app/service/shell/member');
import ExportShellProduct = require('../../../app/service/shell/product');
import ExportUtilsExcel = require('../../../app/service/utils/excel');
import ExportUtilsOlderBaseData = require('../../../app/service/utils/olderBaseData');
import ExportUtilsRedis = require('../../../app/service/utils/redis');

declare module 'egg' {
  interface IService {
    activity: AutoInstanceType<typeof ExportActivity>;
    activityExpand: AutoInstanceType<typeof ExportActivityExpand>;
    alicloudsms: AutoInstanceType<typeof ExportAlicloudsms>;
    card: AutoInstanceType<typeof ExportCard>;
    cardEntity: AutoInstanceType<typeof ExportCardEntity>;
    cardHistory: AutoInstanceType<typeof ExportCardHistory>;
    cardLevel: AutoInstanceType<typeof ExportCardLevel>;
    china: AutoInstanceType<typeof ExportChina>;
    coach: AutoInstanceType<typeof ExportCoach>;
    company: AutoInstanceType<typeof ExportCompany>;
    companyPackage: AutoInstanceType<typeof ExportCompanyPackage>;
    contractTemplete: AutoInstanceType<typeof ExportContractTemplete>;
    coupon: AutoInstanceType<typeof ExportCoupon>;
    course: AutoInstanceType<typeof ExportCourse>;
    courseExpand: AutoInstanceType<typeof ExportCourseExpand>;
    courseCoach: AutoInstanceType<typeof ExportCourseCoach>;
    courseLabel: AutoInstanceType<typeof ExportCourseLabel>;
    coursePackageRelate: AutoInstanceType<typeof ExportCoursePackageRelate>;
    courseSchedule: AutoInstanceType<typeof ExportCourseSchedule>;
    courseType: AutoInstanceType<typeof ExportCourseType>;
    email163: AutoInstanceType<typeof ExportEmail163>;
    faceDevice: AutoInstanceType<typeof ExportFaceDevice>;
    faceDeviceExtend: AutoInstanceType<typeof ExportFaceDeviceExtend>;
    geographic: AutoInstanceType<typeof ExportGeographic>;
    home: AutoInstanceType<typeof ExportHome>;
    icons: AutoInstanceType<typeof ExportIcons>;
    label: AutoInstanceType<typeof ExportLabel>;
    member: AutoInstanceType<typeof ExportMember>;
    memberExpand: AutoInstanceType<typeof ExportMemberExpand>;
    memberBody: AutoInstanceType<typeof ExportMemberBody>;
    memberCoachInvite: AutoInstanceType<typeof ExportMemberCoachInvite>;
    memberCoupon: AutoInstanceType<typeof ExportMemberCoupon>;
    memberMessage: AutoInstanceType<typeof ExportMemberMessage>;
    memberReservation: AutoInstanceType<typeof ExportMemberReservation>;
    memberReservationExpand: AutoInstanceType<typeof ExportMemberReservationExpand>;
    memberTracking: AutoInstanceType<typeof ExportMemberTracking>;
    migrate: AutoInstanceType<typeof ExportMigrate>;
    order: AutoInstanceType<typeof ExportOrder>;
    orderExpand: AutoInstanceType<typeof ExportOrderExpand>;
    orderContract: AutoInstanceType<typeof ExportOrderContract>;
    orderMain: AutoInstanceType<typeof ExportOrderMain>;
    orderPayment: AutoInstanceType<typeof ExportOrderPayment>;
    orderPaymentExpand: AutoInstanceType<typeof ExportOrderPaymentExpand>;
    orderRefund: AutoInstanceType<typeof ExportOrderRefund>;
    orderSub: AutoInstanceType<typeof ExportOrderSub>;
    packageStore: AutoInstanceType<typeof ExportPackageStore>;
    packages: AutoInstanceType<typeof ExportPackages>;
    packagesType: AutoInstanceType<typeof ExportPackagesType>;
    placeOrder: AutoInstanceType<typeof ExportPlaceOrder>;
    store: AutoInstanceType<typeof ExportStore>;
    storeRoom: AutoInstanceType<typeof ExportStoreRoom>;
    storeTask: AutoInstanceType<typeof ExportStoreTask>;
    sysCache: AutoInstanceType<typeof ExportSysCache>;
    sysCacheExpand: AutoInstanceType<typeof ExportSysCacheExpand>;
    sysDepartment: AutoInstanceType<typeof ExportSysDepartment>;
    sysDictionary: AutoInstanceType<typeof ExportSysDictionary>;
    sysLog: AutoInstanceType<typeof ExportSysLog>;
    sysMenu: AutoInstanceType<typeof ExportSysMenu>;
    sysMenuSysOperation: AutoInstanceType<typeof ExportSysMenuSysOperation>;
    sysMenuSysRoleSysOperation: AutoInstanceType<typeof ExportSysMenuSysRoleSysOperation>;
    sysMessage: AutoInstanceType<typeof ExportSysMessage>;
    sysNavigation: AutoInstanceType<typeof ExportSysNavigation>;
    sysOperation: AutoInstanceType<typeof ExportSysOperation>;
    sysRole: AutoInstanceType<typeof ExportSysRole>;
    sysRoleSysUser: AutoInstanceType<typeof ExportSysRoleSysUser>;
    sysUser: AutoInstanceType<typeof ExportSysUser>;
    sysUserDutyRoster: AutoInstanceType<typeof ExportSysUserDutyRoster>;
    sysUserLabel: AutoInstanceType<typeof ExportSysUserLabel>;
    system: AutoInstanceType<typeof ExportSystem>;
    task: AutoInstanceType<typeof ExportTask>;
    taskRecord: AutoInstanceType<typeof ExportTaskRecord>;
    taskType: AutoInstanceType<typeof ExportTaskType>;
    test: AutoInstanceType<typeof ExportTest>;
    trainAction: AutoInstanceType<typeof ExportTrainAction>;
    trainSchedulePhase: AutoInstanceType<typeof ExportTrainSchedulePhase>;
    trainSchedulePhaseAction: AutoInstanceType<typeof ExportTrainSchedulePhaseAction>;
    trainScheduleUser: AutoInstanceType<typeof ExportTrainScheduleUser>;
    trainTplPhase: AutoInstanceType<typeof ExportTrainTplPhase>;
    trainTplPhaseAction: AutoInstanceType<typeof ExportTrainTplPhaseAction>;
    trainTplSchedule: AutoInstanceType<typeof ExportTrainTplSchedule>;
    userRight: AutoInstanceType<typeof ExportUserRight>;
    verification: AutoInstanceType<typeof ExportVerification>;
    wechatFormId: AutoInstanceType<typeof ExportWechatFormId>;
    wxpayRecord: AutoInstanceType<typeof ExportWxpayRecord>;
    code: {
      index: AutoInstanceType<typeof ExportCodeIndex>;
    }
    message: {
      orderSuccess: AutoInstanceType<typeof ExportMessageOrderSuccess>;
    }
    payment: {
      wxpay: AutoInstanceType<typeof ExportPaymentWxpay>;
    }
    shell: {
      cart: AutoInstanceType<typeof ExportShellCart>;
      member: AutoInstanceType<typeof ExportShellMember>;
      product: AutoInstanceType<typeof ExportShellProduct>;
    }
    utils: {
      excel: AutoInstanceType<typeof ExportUtilsExcel>;
      olderBaseData: AutoInstanceType<typeof ExportUtilsOlderBaseData>;
      redis: AutoInstanceType<typeof ExportUtilsRedis>;
    }
  }
}
