'use strict';
// todo: 把id 写死，以后应该可以随时执行
const { getSha1 } = require('../../utils/index')
const uuid = require('uuid');

/* 菜单*/
let data = {
    "menu": [{
            "Id": "",
            "Name": "首页",
            "ParentId": null,
            "Url": "",
            "Iconic": "",
            "Sort": 100,
            "Remark": "首页",
            "State": 1,
            "IsHomePage": 0,
            "Valid": 1,
            "CreateTime": Date.now(),
            "CreatePerson": "init-system",
            "UpdateTime": null,
            "UpdatePerson": "init-system",
            "children": [{
                "Id": "",
                "Name": "系统首页",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "系统首页",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "工作台",
                    "ParentId": null,
                    "Url": "/home",
                    "Iconic": "home",
                    "Sort": 1,
                    "Remark": "工作台",
                    "State": 1,
                    "IsHomePage": 1,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "账号设置",
                    "ParentId": null,
                    "Url": "/user/changepwd",
                    "Iconic": "account",
                    "Sort": 0,
                    "Remark": "工作台2",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }, {
                "Id": "",
                "Name": "部门用户",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "部门用户",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "系统用户",
                    "ParentId": null,
                    "Url": "/page/sysperson/manage",
                    "Iconic": "team",
                    "Sort": 0,
                    "Remark": "系统用户",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "部门管理",
                    "ParentId": null,
                    "Url": "/page/sysdepartment/manage",
                    "Iconic": "user",
                    "Sort": 0,
                    "Remark": "部门管理",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "权限管理",
                    "ParentId": null,
                    "Url": "/user/role-right",
                    "Iconic": "user",
                    "Sort": 0,
                    "Remark": "权限管理",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "用户角色管理",
                    "ParentId": null,
                    "Url": "/page/sysrolesysperson/manage",
                    "Iconic": "user",
                    "Sort": 0,
                    "Remark": "用户角色管理",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }, {
                "Id": "",
                "Name": "系统运营",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "系统运营",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "区块高度",
                    "ParentId": null,
                    "Url": "/page/cnh_blockchainheight/manage",
                    "Iconic": "team",
                    "Sort": 0,
                    "Remark": "区块高度",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                },
                {
                    "Id": "",
                    "Name": "订单状态管理",
                    "ParentId": null,
                    "Url": "/page/cnh_userorderstatus/manage",
                    "Iconic": "user",
                    "Sort": 0,
                    "Remark": "订单状态管理",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            },{
                "Id": "",
                "Name": "开发管理",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "开发管理",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "系统菜单管理",
                    "ParentId": null,
                    "Url": "/page/sysmenu/manage",
                    "Iconic": "team",
                    "Sort": 0,
                    "Remark": "系统菜单管理",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "页面操作管理",
                    "ParentId": null,
                    "Url": "/page/sysoperation/manage",
                    "Iconic": "user",
                    "Sort": 0,
                    "Remark": "页面操作管理",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "系统日志",
                    "ParentId": null,
                    "Url": "/page/syslog/manage",
                    "Iconic": "user",
                    "Sort": 0,
                    "Remark": "系统日志",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }]
        },
        {
            "Id": "",
            "Name": "合约",
            "ParentId": null,
            "Url": "",
            "Iconic": "",
            "Sort": 90,
            "Remark": "合约",
            "State": 1,
            "IsHomePage": 0,
            "Valid": 1,
            "CreateTime": Date.now(),
            "CreatePerson": "init-system",
            "UpdateTime": null,
            "UpdatePerson": "init-system",
            "children": [{
                "Id": "",
                "Name": "合约",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "产品",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "合约列表",
                    "ParentId": null,
                    "Url": "/page/cnh_product/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "合约列表",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "添加合约",
                    "ParentId": null,
                    "Url": "/product/create",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "添加合约",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "合约审核",
                    "ParentId": null,
                    "Url": "/page/cnh_product/manage?Approval=3",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "合约审核",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "合约协议",
                    "ParentId": null,
                    "Url": "/page/cnh_contract/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "合约协议",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "创建协议",
                    "ParentId": null,
                    "Url": "/page/cnh_contract/create",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "创建协议",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "合约类型",
                    "ParentId": null,
                    "Url": "/page/cnh_producttypes/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "合约类型",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }]
        },
        {
            "Id": "",
            "Name": "订单",
            "ParentId": null,
            "Url": "",
            "Iconic": "",
            "Sort": 80,
            "Remark": "订单",
            "State": 1,
            "IsHomePage": 0,
            "Valid": 1,
            "CreateTime": Date.now(),
            "CreatePerson": "init-system",
            "UpdateTime": null,
            "UpdatePerson": "init-system",
            "children": [{
                "Id": "",
                "Name": "订单",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "产品",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "订单列表",
                    "ParentId": null,
                    "Url": "/page/cnh_userorder/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "订单列表",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }]
        },
        {
            "Id": "",
            "Name": "用户",
            "ParentId": null,
            "Url": "",
            "Iconic": "",
            "Sort": 70,
            "Remark": "用户",
            "State": 1,
            "IsHomePage": 0,
            "Valid": 1,
            "CreateTime": Date.now(),
            "CreatePerson": "init-system",
            "UpdateTime": null,
            "UpdatePerson": "init-system",
            "children": [{
                "Id": "",
                "Name": "用户列表",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "用户列表",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "用户列表",
                    "ParentId": null,
                    "Url": "/page/cnh_user/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "用户列表",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }]
        },
        {
            "Id": "",
            "Name": "运营",
            "ParentId": null,
            "Url": "",
            "Iconic": "",
            "Sort": 60,
            "Remark": "运营",
            "State": 1,
            "IsHomePage": 0,
            "Valid": 1,
            "CreateTime": Date.now(),
            "CreatePerson": "init-system",
            "UpdateTime": null,
            "UpdatePerson": "init-system",
            "children": [{
                "Id": "",
                "Name": "广告管理",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "广告管理",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "广告管理",
                    "ParentId": null,
                    "Url": "/page/cnh_banners/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "广告管理",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "新建广告",
                    "ParentId": null,
                    "Url": "/page/cnh_banners/create",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "新建广告",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            },{
                "Id": "",
                "Name": "公告管理",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "公告管理",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "公告管理",
                    "ParentId": null,
                    "Url": "/page/sysannouncement/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "公告管理",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "新建公告",
                    "ParentId": null,
                    "Url": "/page/sysannouncement/create",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "新建公告",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            },{
                "Id": "",
                "Name": "消息管理",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "消息管理",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "短信消息",
                    "ParentId": null,
                    "Url": "/page/cnh_messagerecord/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "短信消息",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                },{
                    "Id": "",
                    "Name": "短信模板",
                    "ParentId": null,
                    "Url": "/page/sysmessagetemp/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "短信消息",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "邮件消息",
                    "ParentId": null,
                    "Url": "/page/cnh_emailrecord/manage",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "邮件消息",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                },
                {
                    "Id": "",
                    "Name": "邮件模板",
                    "ParentId": null,
                    "Url": "/page/sysemailtemp/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "短信消息",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }]
        },
        {
            "Id": "",
            "Name": "统计",
            "ParentId": null,
            "Url": "",
            "Iconic": "",
            "Sort": 50,
            "Remark": "统计",
            "State": 1,
            "IsHomePage": 0,
            "Valid": 1,
            "CreateTime": Date.now(),
            "CreatePerson": "init-system",
            "UpdateTime": null,
            "UpdatePerson": "init-system",
            "children": [{
                "Id": "",
                "Name": "统计",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "统计",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "订单统计",
                    "ParentId": null,
                    "Url": "/statistics/order",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "订单统计",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "合约统计",
                    "ParentId": null,
                    "Url": "/statistics/contract",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "合约统计",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "会员统计",
                    "ParentId": null,
                    "Url": "/statistics/member",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "会员统计",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "会员排行",
                    "ParentId": null,
                    "Url": "/statistics/membersort",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "会员排行",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }]
        },
        {
            "Id": "",
            "Name": "财务",
            "ParentId": null,
            "Url": "",
            "Iconic": "",
            "Sort": 40,
            "Remark": "财务",
            "State": 1,
            "IsHomePage": 0,
            "Valid": 1,
            "CreateTime": Date.now(),
            "CreatePerson": "init-system",
            "UpdateTime": null,
            "UpdatePerson": "init-system",
            "children": [{
                "Id": "",
                "Name": "财务报表",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 10,
                "Remark": "财务报表",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "订单支付列表",
                    "ParentId": null,
                    "Url": "/page/cnh_userorder/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "订单支付列表",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "收益发放列表",
                    "ParentId": null,
                    "Url": "/finance/profitgrant",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "收益发放列表",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                },{
                    "Id": "",
                    "Name": "手续费",
                    "ParentId": null,
                    "Url": "/finance/commissioncharge",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "手续费",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }, {
                "Id": "",
                "Name": "对账管理",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 5,
                "Remark": "对账管理",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "CNY充值",
                    "ParentId": null,
                    "Url": "/page/cnh_usercnydeposit/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "CNY充值",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "CNY提现",
                    "ParentId": null,
                    "Url": "/page/cnh_usercnywithdrawdeposit/manage",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "CNY提现",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "币充值",
                    "ParentId": null,
                    "Url": "/finance/ciondeposit",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "CNY充值",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "币提现",
                    "ParentId": null,
                    "Url": "/finance/coinwithdraw",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "币提现",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }, {
                "Id": "",
                "Name": "收付款设置",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "收付款设置",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "用户支付设置",
                    "ParentId": null,
                    "Url": "/page/cnh_paymentsetting/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "用户支付设置",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                },{
                    "Id": "",
                    "Name": "汇率设置",
                    "ParentId": null,
                    "Url": "/page/cnh_exchangerate/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "汇率设置",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                },{
                    "Id": "",
                    "Name": "理论收益值设置",
                    "ParentId": null,
                    "Url": "/page/cnh_profitgivesetting/manage",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "理论收益值设置",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "法币收款设置",
                    "ParentId": null,
                    "Url": "/page/cnh_bankaccountsetting/manage",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "法币收款设置",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "提现手续费设置",
                    "ParentId": null,
                    "Url": "/page/cnh_withdrawdeposithandlingfeesetting/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "提现手续费设置",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "邀请奖励设置",
                    "ParentId": null,
                    "Url": "/page/cnh_profitgivesetting/manage",
                    "Iconic": "create",
                    "Sort": 0,
                    "Remark": "邀请奖励设置",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }, {
                "Id": "",
                "Name": "销售挖矿",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "销售挖矿",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "挖矿设置",
                    "ParentId": null,
                    "Url": "/page/cnh_hacmining_setting/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "挖矿设置",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "挖矿发放列表",
                    "ParentId": null,
                    "Url": "/page/cnh_userhacmining/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "挖矿发放列表",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }, {
                    "Id": "",
                    "Name": "交易所汇率",
                    "ParentId": null,
                    "Url": "/page/cnh_hacexchange/manage",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "交易所汇率",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }]
        }, {
            "Id": "",
            "Name": "设置",
            "ParentId": null,
            "Url": "",
            "Iconic": "",
            "Sort": 30,
            "Remark": "设置",
            "State": 1,
            "IsHomePage": 0,
            "Valid": 1,
            "CreateTime": Date.now(),
            "CreatePerson": "init-system",
            "UpdateTime": null,
            "UpdatePerson": "init-system",
            "children": [{
                "Id": "",
                "Name": "设置",
                "ParentId": null,
                "Url": "",
                "Iconic": "",
                "Sort": 0,
                "Remark": "设置",
                "State": 1,
                "IsHomePage": 0,
                "Valid": 1,
                "CreateTime": Date.now(),
                "CreatePerson": "init-system",
                "UpdateTime": null,
                "UpdatePerson": "init-system",
                "children": [{
                    "Id": "",
                    "Name": "基本设置",
                    "ParentId": null,
                    "Url": "/setting/base",
                    "Iconic": "manage",
                    "Sort": 0,
                    "Remark": "基本设置",
                    "State": 1,
                    "IsHomePage": 0,
                    "Valid": 1,
                    "CreateTime": Date.now(),
                    "CreatePerson": "init-system",
                    "UpdateTime": null,
                    "UpdatePerson": "init-system"
                }]
            }]
        }
    ]
}

/* 部门*/
data.sysdepartment = [{
    Id: uuid.v4(),
    Name: "技术部",
    ParentId: null,
    Address: "阳光科创中心",
    Sort: 1,
    Remark: "开发",
    Valid: 1,
    CreateTime: 1531026705646,
    CreatePerson: "admin",
    UpdateTime: 1531026705646,
    UpdatePerson: "admin"
}];

/* 管理员 */
data.sysperson = [{
    Id: uuid.v4(),
    Name: "admin",
    MyName: "管理员",
    Password: getSha1("123456" + "admin"),
    Sex: "男",
    SysDepartmentId: data.sysdepartment.Id,
    Position: "IT",
    MobilePhoneNumber: "19925481257",
    PhoneNumber: "19925481257",
    Province: "广东",
    City: "深圳市",
    Village: "南山区",
    Address: "阳光科创中心",
    EmailAddress: "yu@126.com",
    Remark: "",
    State: "1",
    LogonNum: 2,
    LogonTime: 1531026705650,
    LogonIP: "1.1.1.1",
    LastLogonTime: 1531026705650,
    LastLogonIP: "1.1.1.1",
    PageStyle: "显示",
    HDpic: "test",
    Valid: 1,
    CreateTime: 1531026705650,
    CreatePerson: "admin",
    UpdateTime: 1531026705650,
    UpdatePerson: "admin"
}];

/* data sysoperation */
data.sysoperation = [
   {
        Id: '1',
        Name: "添加",
        Function: "Create",
        Iconic: "Create",
        Sort: 0,
        Remark: "Create Button",
        State: "1",
        Valid: 1,
        CreateTime: Date.now(),
        CreatePerson: "admin"
    },{
        Id: '2',
        Name: "编辑",
        Function: "Edit",
        Iconic: "Edit",
        Sort: 0,
        Remark: "Edit Button",
        State: "1",
        Valid: 1,
        CreateTime: Date.now(),
        CreatePerson: "admin"
    },{
        Id: '3',
        Name: "详情",
        Function: "Detail",
        Iconic: "Detail",
        Sort: 0,
        Remark: "Detail Button",
        State: "1",
        Valid: 1,
        CreateTime: Date.now(),
        CreatePerson: "admin"
    },{
        Id: '4',
        Name: "删除",
        Function: "Delete",
        Iconic: "Delete",
        Sort: 0,
        Remark: "Delete Button",
        State: "1",
        Valid: 1,
        CreateTime: Date.now(),
        CreatePerson: "admin"
    },{
        Id: '5',
        Name: "查询",
        Function: "Search",
        Iconic: "Search",
        Sort: 0,
        Remark: "Search Button",
        State: "1",
        Valid: 1,
        CreateTime: Date.now(),
        CreatePerson: "admin"
    },{
        Id: '6',
        Name: "导出Excel",
        Function: "Export",
        Iconic: "Export",
        Sort: 0,
        Remark: "Export Button",
        State: "1",
        Valid: 1,
        CreateTime: Date.now(),
        CreatePerson: "admin"
    },{
        Id: '7',
        Name: "显示",
        Function: "Show",
        Iconic: "Show",
        Sort: 0,
        Remark: "Show Button",
        State: "1",
        Valid: 1,
        CreateTime: Date.now(),
        CreatePerson: "admin"
    },{
        Id: '8',
        Name: "保存",
        Function: "Save",
        Iconic: "Save",
        Sort: 0,
        Remark: "Save Button",
        State: "1",
        Valid: 1,
        CreateTime: Date.now(),
        CreatePerson: "admin"
    }
]

/* data sysrole */
data.sysrole = [
    {
        Id: uuid.v4(),
        Name: "超级管理员",
        Description: "超级管理员",
        Valid: 1,
        CreateTime: Date.now(),
        CreatePerson: "admin",
        UpdateTime: Date.now(),
        UpdatePerson: "admin"
    },{
        Id: uuid.v4(),
        Name: "管理员",
        Description: "管理员",
        Valid: 1,
        CreateTime: Date.now(),
        CreatePerson: "admin",
        UpdateTime: Date.now(),
        UpdatePerson: "admin"
    },{
        Id: uuid.v4(),
        Name: "运营",
        Description: "运营",
        Valid: 1,
        CreateTime: Date.now(),
        CreatePerson: "admin",
        UpdateTime: Date.now(),
        UpdatePerson: "admin"
    }
]

/* 角色用户 */
data.sysrolesysperson = [{
    Id: uuid.v4(),
    SysPersonId:  data.sysperson[0].Id,
    SysRoleId: data.sysrole[0].Id,
    CreateTime: Date.now(),
    CreatePerson: "admin",
    Valid: 1
}]


var createEntityList = (array, parentId) => {

    const curParentId = parentId || null;
    if (!array) {
        throw Error("param should be array")
    }
    let entityList = [];

    for (var i = 0; i < array.length; i++) {
        let curEnity = array[i];
        let newEntity = {};
        for (var f in curEnity) {
            if (f !== 'children') {
                newEntity[f] = curEnity[f];
            }
        }
        newEntity.Id = uuid.v4();
        newEntity.ParentId = curParentId;
        if(typeof newEntity['Sort'] !== 'undefined') {
            newEntity['Sort'] = (array.length - i);
        }
        entityList.push(newEntity);
        if (curEnity.children) {
            entityList = entityList.concat(createEntityList(curEnity.children, newEntity.Id))
        }
    }
    return entityList;
}

module.exports = {
    data,
    createEntityList,
    getMenuEntityList: () => {
        return createEntityList(data.menu, null);
    },
    getDepartmentList: () => {
        return data.sysdepartment;
    },
    getSyspersionList: () => {
        return data.sysperson;
    },
    getSysoperation: () => {
        return data.sysoperation;
    },
    getSysrole: () => {
        return data.sysrole;
    },
    getSysrolesysperson: () => {
        return data.sysrolesysperson;
    }
}
